# Generated by Django 2.2.4 on 2020-09-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotedBy', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('addedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addedQuotes', to='quotesapp.User')),
                ('favoritedBy', models.ManyToManyField(related_name='favorites', to='quotesapp.User')),
            ],
        ),
    ]
